# Generated by Django 4.0.4 on 2022-06-02 22:26

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0002_alter_imagen_image_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userweb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('first_name', models.CharField(help_text='First Name', max_length=100)),
                ('last_name', models.CharField(help_text='First Name', max_length=100)),
                ('birthday', models.DateTimeField(help_text='Birthday Person', unique=True)),
                ('cell_phone', models.CharField(help_text='3100000000', max_length=10)),
                ('email_user', models.EmailField(help_text='Email Person', max_length=254, unique=True)),
                ('date_create_user', models.DateTimeField(verbose_name='Date Create User')),
            ],
        ),
    ]
